plugin:
    name: 'xitara.snippetpool::lang.plugin.name'
    description: 'xitara.snippetpool::lang.plugin.description'
    author: 'xitara.snippetpool::lang.plugin.author'
    homepage: 'xitara.snippetpool::lang.plugin.homepage'
