# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Group

# Model Form Field configuration
form: $/xitara/snippetpool/models/group/fields.yaml

# Model Class name
modelClass: Xitara\SnippetPool\Models\Group

# Default redirect location
defaultRedirect: xitara/snippetpool/group

# Create page
create:
    title: Create Group
    redirect: xitara/snippetpool/group/update/:id
    redirectClose: xitara/snippetpool/group

# Update page
update:
    title: Edit Group
    redirect: xitara/snippetpool/group
    redirectClose: xitara/snippetpool/group

# Preview page
preview:
    title: Preview Group
