name: Content
modelClass: Xitara\Toolbox\Models\Content
form: $/xitara/toolbox/models/content/content_form.yaml
defaultRedirect: xitara/toolbox/content
create:
    redirect: 'xitara/toolbox/content/update/:id'
    redirectClose: xitara/toolbox/content
update:
    redirect: xitara/toolbox/content
    redirectClose: xitara/toolbox/content
