title: Snippets
modelClass: Xitara\SnippetPool\Models\Snippets
list: $/xitara/snippetpool/models/snippets/columns.yaml
recordUrl: 'xitara/snippetpool/snippets/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
