name: Snippets
modelClass: Xitara\SnippetPool\Models\Snippets
form: $/xitara/snippetpool/models/snippets/fields.yaml
defaultRedirect: xitara/snippetpool/snippets
create:
    redirect: 'xitara/snippetpool/snippets/update/:id'
    redirectClose: xitara/snippetpool/snippets
update:
    redirect: xitara/snippetpool/snippets
    redirectClose: xitara/snippetpool/snippets
preview: {  }
